{"name":"createduplicateuser","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [New User User29 created Successfully] but found [User already exist!]","trace":"java.lang.AssertionError: expected [New User User29 created Successfully] but found [User already exist!]\r\n\tat org.testng.Assert.fail(Assert.java:96)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:776)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:137)\r\n\tat org.testng.Assert.assertEquals(Assert.java:118)\r\n\tat org.testng.Assert.assertEquals(Assert.java:453)\r\n\tat org.testng.Assert.assertEquals(Assert.java:463)\r\n\tat com.enhanzedadmin.qa.pages.CreateUser.createduplicateUser(CreateUser.java:191)\r\n\tat com.enhanzedadmin.qa.testcases.ManageUserTest.createduplicateuser(ManageUserTest.java:201)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:583)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:648)\r\n\tat org.testng.TestRunner.run(TestRunner.java:505)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:455)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:364)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1137)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1049)\r\n\tat org.testng.TestNG.run(TestNG.java:1017)\r\n\tat org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)\r\n\tat org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)\r\n\tat org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)\r\n"},"stage":"finished","description":"To check for create user","steps":[],"attachments":[],"parameters":[{"name":"arg3","value":"test"},{"name":"arg2","value":"1.2345678E7"},{"name":"arg1","value":"user29@email.com"},{"name":"arg0","value":"User29"}],"start":1576828394668,"stop":1576828409618,"uuid":"84749789-cd8a-4634-866d-6dab223f9699","historyId":"2769e0bb47c4da033d993e6c0415fa4a","fullName":"com.enhanzedadmin.qa.testcases.ManageUserTest.createduplicateuser","labels":[{"name":"package","value":"com.enhanzedadmin.qa.testcases.ManageUserTest"},{"name":"testClass","value":"com.enhanzedadmin.qa.testcases.ManageUserTest"},{"name":"testMethod","value":"createduplicateuser"},{"name":"parentSuite","value":"suite"},{"name":"suite","value":"Enhanzed admin test"},{"name":"subSuite","value":"com.enhanzedadmin.qa.testcases.ManageUserTest"},{"name":"host","value":"DESKTOP-UQCRR3T"},{"name":"thread","value":"10312@DESKTOP-UQCRR3T.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"severity","value":"critical"}],"links":[]}