<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-UQCRR3T" name="com.enhanzedadmin.qa.testcases.ContentManagecategorytest" tests="44" failures="3" timestamp="8 Jan 2020 09:17:45 GMT" time="1688.546" errors="1">
  <testcase name="checkaddingblanksubcategory" time="35.508" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkaddingDuplicateSubcategory" time="39.568" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkaddingDuplicateSubcategory" time="37.301" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkdeletingcategory" time="32.876" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkaddingDuplicateSubcategory" time="38.989" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkAddCategoryPopUpUI" time="34.824" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkadddSubcategory" time="37.449" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkEditCategory" time="32.936" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest">
    <failure type="java.lang.AssertionError" message="expected [Category edited Successfully] but found [Category edited successfully]">
      <![CDATA[java.lang.AssertionError: expected [Category edited Successfully] but found [Category edited successfully]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.enhanzedadmin.qa.pages.ContentManageCategories.checkEditingcategorybyspace(ContentManageCategories.java:319)
	at com.enhanzedadmin.qa.testcases.ContentManagecategorytest.checkEditCategory(ContentManagecategorytest.java:227)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- checkEditCategory -->
  <testcase name="checkdeleteSubcategory" time="34.463" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkadddSubcategory" time="40.942" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkaddingDuplicateSubcategory" time="42.830" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkadddSubcategory" time="37.584" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkEditSubcategory" time="35.136" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkEditSubcategory" time="34.758" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkaddingDuplicateSubcategory" time="40.143" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkCategoryUI" time="33.014" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest">
    <error type="java.lang.Error" message="Unresolved compilation problem: 
	The method checkListcategory() is undefined for the type ContentManageCategories
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
	The method checkListcategory() is undefined for the type ContentManageCategories

	at com.enhanzedadmin.qa.testcases.ContentManagecategorytest.checkCategoryUI(ContentManagecategorytest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- checkCategoryUI -->
  <testcase name="checkdeletingcategory" time="33.290" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkAddingDuplicateCategory" time="48.413" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkdeletingcategory" time="32.641" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkadddSubcategory" time="38.395" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkcorrecterrormessge" time="35.016" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkadddSubcategory" time="40.007" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkErrormessages" time="33.131" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkAddingcategory" time="52.274" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkaddingDuplicateSubcategory" time="37.210" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkerormessageforcategoryimage" time="31.739" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkadddSubcategory" time="37.330" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkAddSubcategoryUI" time="37.886" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkEditCategory" time="33.608" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest">
    <failure type="java.lang.AssertionError" message="expected [Category edited Successfully] but found [Category edited successfully]">
      <![CDATA[java.lang.AssertionError: expected [Category edited Successfully] but found [Category edited successfully]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.enhanzedadmin.qa.pages.ContentManageCategories.checkEditingcategorybyspace(ContentManageCategories.java:319)
	at com.enhanzedadmin.qa.testcases.ContentManagecategorytest.checkEditCategory(ContentManagecategorytest.java:227)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- checkEditCategory -->
  <testcase name="checkForcategorynameErrormsg" time="40.745" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkadddSubcategory" time="40.344" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkaddingDuplicateSubcategory" time="37.633" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkdeleteSubcategory" time="33.100" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkAddingDuplicateCategory" time="46.913" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkAddingcategory" time="52.310" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkAddingcategory" time="50.585" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkEditSubcategory" time="38.700" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkdeleteSubcategory" time="34.332" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkEditCategory" time="33.176" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest">
    <failure type="java.lang.AssertionError" message="expected [Category edited Successfully] but found [Category edited successfully]">
      <![CDATA[java.lang.AssertionError: expected [Category edited Successfully] but found [Category edited successfully]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.enhanzedadmin.qa.pages.ContentManageCategories.checkEditingcategorybyspace(ContentManageCategories.java:319)
	at com.enhanzedadmin.qa.testcases.ContentManagecategorytest.checkEditCategory(ContentManagecategorytest.java:227)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- checkEditCategory -->
  <testcase name="checkadddSubcategory" time="37.845" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkaddingDuplicateSubcategory" time="38.966" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkaddingDuplicateSubcategory" time="41.338" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkadddSubcategory" time="35.673" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
  <testcase name="checkAddingDuplicateCategory" time="47.625" classname="com.enhanzedadmin.qa.testcases.ContentManagecategorytest"/>
</testsuite> <!-- com.enhanzedadmin.qa.testcases.ContentManagecategorytest -->
